name: 'Release Plugin'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version v'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Embed version info
      run: echo "${{ github.sha }}" > ConfusedPolarBear.Plugin.IntroSkipper/Configuration/version.txt

    - name: Build
      run: dotnet build --no-restore

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ConfusedPolarBear.Plugin.IntroSkipper-v${{ github.event.inputs.version }}.dll
        path: ConfusedPolarBear.Plugin.IntroSkipper/bin/Debug/net6.0/ConfusedPolarBear.Plugin.IntroSkipper.dll
        if-no-files-found: error

    - name: Create archive
      uses: vimtor/action-zip@v1.2
      with:
        files: |
          ConfusedPolarBear.Plugin.IntroSkipper/bin/Debug/net6.0/ConfusedPolarBear.Plugin.IntroSkipper.dll
        dest: intro-skipper-v${{ github.event.inputs.version }}.zip

    - name: Generate manifest keys
      run: |
        sourceUrl="https://github.com/${{ github.repository }}/releases/download/10.8/v${{ github.event.inputs.version }}/intro-skipper-v${{ github.event.inputs.version }}.zip"
        echo "SOURCE_URL=$sourceUrl" >> $GITHUB_ENV
        md5sum intro-skipper-v${{ github.event.inputs.version }}.zip > intro-skipper-v${{ github.event.inputs.version }}.md5
        checksum="$(awk '{print $1}' intro-skipper-v${{ github.event.inputs.version }}.md5)"
        echo "CHECKSUM=$checksum" >> $GITHUB_ENV
        timestamp="$(date +%FT%TZ)"
        echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

    - name: Publish release
      uses: 8bitDream/action-github-releases@v1.0.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 10.8/v${{ github.event.inputs.version }}
        prerelease: false
        title: v${{ github.event.inputs.version }}
        files: |
          intro-skipper-v${{ github.event.inputs.version }}.zip

    - name: Publish release notes
      uses: softprops/action-gh-release@v2.0.5
      with:
        tag_name: 10.8/v${{ github.event.inputs.version }}
        name: v${{ github.event.inputs.version }}
        append_body: true
        body: |
          ---
          ```json
            {
                "version": "${{ github.event.inputs.version }}",
                "changelog": "- See the full changelog at [GitHub](https://github.com/jumoog/intro-skipper/blob/master/CHANGELOG.md)\n",
                "targetAbi": "10.8.4.0",
                "sourceUrl": "${{ env.SOURCE_URL }}",
                "checksum": "${{ env.CHECKSUM }}",
                "timestamp": "${{ env.TIMESTAMP }}"
            }
          ```
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

